 const Facebook_login_success='facebook_login_success'
 const Facebook_login_fail='facebook_login_fail'
 const order_coffee='sending_coffee_order'
 const ORDER_BEGIN = 'ORDER_BEGIN'
 const ORDER_SUCCESS = 'ORDER_SENT'
 const ORDER_CANCELLED = 'TOGGLE_THEME_SUCCESS'
 const ORDER_FAILED = 'ORDER_FAILED'

 const TOGGLE_THEME_BEGIN = 'TOGGLE_THEME_BEGIN'
 const TOGGLE_THEME_SUCCESS = 'TOGGLE_THEME_SUCCESS'
 const TOGGLE_THEME_FAILURE = 'TOGGLE_THEME_FAILURE'

//ORDER
const ADD_COFFEE_TYPE='ADD_COFFEE_TYPE'

//LOGINS
const HANDLE_FBLOGIN='HANDLE_FBLOGIN'
const FACEBOOK_LOGIN_SUCCESS = 'Facebook_login_success'
const FACEBOOK_LOGIN_FAIL = 'Facebook_login_fail'
const HANDLE_MANUAL_REGISTRY='HANDLE_MANUAL_REGISTRY'
const MANUAL_REGISTRY_SUCCESS='MANUAL_REGISTRY_SUCCESS'
const MANUAL_REGISTRY_FAILURE='MANUAL_REGISTRY_FAILURE'

//EXPORT
export { 
        ADD_COFFEE_TYPE,
        HANDLE_FBLOGIN,FACEBOOK_LOGIN_FAIL,FACEBOOK_LOGIN_SUCCESS,
        TOGGLE_THEME_BEGIN,TOGGLE_THEME_SUCCESS,TOGGLE_THEME_FAILURE,
        HANDLE_MANUAL_REGISTRY,MANUAL_REGISTRY_SUCCESS,MANUAL_REGISTRY_FAILURE}